id: A746EB42D
title: CIII_Mahatī Sīmā
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.215447
  last_modified_at: 2022-03-01 22:13:34.215455
