id: A746EB42D
title: CI_Uddāna
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.401870
  last_modified_at: 2022-03-01 22:13:34.401872
