id: A746EB42D
title: CIII_Poṣadha for few monks, purity
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.224441
  last_modified_at: 2022-03-01 22:13:34.224444
