id: A746EB42D
title: CII_Tṛdaṇḍaka
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.397783
  last_modified_at: 2022-03-01 22:13:34.397786
