id: A746EB42D
title: CIII_c6
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.343613
  last_modified_at: 2022-03-01 22:13:34.343616
