id: A746EB42D
title: CII_Resting
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.393745
  last_modified_at: 2022-03-01 22:13:34.393747
