id: A746EB42D
title: CIII_Persons who disturb the Poṣadha
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.220798
  last_modified_at: 2022-03-01 22:13:34.220801
