id: A746EB42D
title: CIII_Nidāna
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.219603
  last_modified_at: 2022-03-01 22:13:34.219608
