id: A746EB42D
title: CIII_Relations of visiting and resident monks during the Poṣadha
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.276274
  last_modified_at: 2022-03-01 22:13:34.276281
