id: A746EB42D
title: CIII_Definition of kriyā
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.204602
  last_modified_at: 2022-03-01 22:13:34.204604
