id: A746EB42D
title: CIII_Where to go and not to go during the Poṣadha day
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.289055
  last_modified_at: 2022-03-01 22:13:34.289058
