id: A746EB42D
title: CII_Rules for meditation
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.395217
  last_modified_at: 2022-03-01 22:13:34.395220
