id: A746EB42D
title: CII_Ordering of ni攷므dy캐, kriy캐 and po攷므dha
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.385262
  last_modified_at: 2022-03-01 22:13:34.385265
