id: A746EB42D
title: CIII_S훮ntarbahirmukh카 S카m훮
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:13:34.282437
  last_modified_at: 2022-03-01 22:13:34.282440
